/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.course.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Course service. Represents a row in the &quot;Course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.course.model.impl.CourseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.course.model.impl.CourseImpl}.
 * </p>
 *
 * @author ces
 * @see Course
 * @see com.liferay.course.model.impl.CourseImpl
 * @see com.liferay.course.model.impl.CourseModelImpl
 * @generated
 */
public interface CourseModel extends BaseModel<Course> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course model instance should use the {@link Course} interface instead.
	 */

	/**
	 * Returns the primary key of this course.
	 *
	 * @return the primary key of this course
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course.
	 *
	 * @param primaryKey the primary key of this course
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the course ID of this course.
	 *
	 * @return the course ID of this course
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course.
	 *
	 * @param courseId the course ID of this course
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the name of this course.
	 *
	 * @return the name of this course
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this course.
	 *
	 * @param name the name of this course
	 */
	public void setName(String name);

	/**
	 * Returns the description of this course.
	 *
	 * @return the description of this course
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this course.
	 *
	 * @param description the description of this course
	 */
	public void setDescription(String description);

	/**
	 * Returns the lecturer of this course.
	 *
	 * @return the lecturer of this course
	 */
	@AutoEscape
	public String getLecturer();

	/**
	 * Sets the lecturer of this course.
	 *
	 * @param lecturer the lecturer of this course
	 */
	public void setLecturer(String lecturer);

	/**
	 * Returns the duration of this course.
	 *
	 * @return the duration of this course
	 */
	public int getDuration();

	/**
	 * Sets the duration of this course.
	 *
	 * @param duration the duration of this course
	 */
	public void setDuration(int duration);

	/**
	 * Returns the status of this course.
	 *
	 * @return the status of this course
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this course is status.
	 *
	 * @return <code>true</code> if this course is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this course is status.
	 *
	 * @param status the status of this course
	 */
	public void setStatus(boolean status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Course course);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Course> toCacheModel();

	@Override
	public Course toEscapedModel();

	@Override
	public Course toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}